const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const url = require('url');

const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = path.resolve(process.env.DATA_DIR || path.join(process.cwd(), 'data'));
const UPLOAD_DIR = path.join(DATA_DIR, 'uploads');
const PUBLIC_DIR = path.join(__dirname, 'public');
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@renegadeair.local';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'ChangeMe123!';
const SESSION_SECRET = process.env.SESSION_SECRET || 'replace-this-session-secret-before-production';
fs.mkdirSync(UPLOAD_DIR, { recursive: true });

const DB_FILE = path.join(DATA_DIR, 'site-data.json');
const defaultData = {
  settings: {
    companyName: 'RENEGADE AIR', tagline: 'Fly More. Travel Smarter.', slogan: 'Your Journey, Our Commitment.',
    phone: '0738 021 474', whatsapp: '254738021474', email: '', address: '',
    heroTitle: 'FLY MORE. TRAVEL SMARTER.', heroText: 'Affordable air travel to selected destinations across Kenya.',
    heroImage: '', logo: '', favicon: '', aboutTitle: 'Your Journey, Our Commitment.',
    aboutText: 'Renegade Air connects travelers to selected destinations across Kenya with a simple, customer-focused booking experience.',
    reviewCount: '7544', reviewCountIsDemo: false, showFleet: true, showGallery: true, showReviews: true
  },
  destinations: [
    ['Eldoret',5500],['Kisumu',6500],['Mombasa',6500],['Kitale',7000],['Homa Bay',7800],['Wajir',9000],['Maasai Mara',10000]
  ].map((x,i)=>({id:Date.now()+i,name:x[0],fare:x[1],description:'A destination listed by Renegade Air.',image:'',active:true,sort:i})),
  gallery: [], fleet: [],
  reviews: [
    ['Mark Otieno','Smooth booking experience and clear travel information.',5],['Kelvin Kiplangat','The booking request was simple and easy to complete.',5],['Brian Mwangi','Easy to find the destination and fare details.',5],
    ['Faith Wanjiku','Helpful communication and a straightforward inquiry process.',4],['Sharon Chebet','I liked how easy it was to contact the team.',5],['Daniel Kiplagat','Clear information and a convenient booking experience.',5],
    ['Mercy Achieng','The destination details are easy to understand.',4],['Kevin Mutua','Quick and simple way to make a travel inquiry.',5],['Ann Njeri','The website makes planning a trip feel easy.',5],
    ['Victor Omondi','Clean layout with the information I needed.',4],['Lucy Wambui','Convenient contact options and simple navigation.',5],['Samuel Kiptoo','Easy to browse destinations and start a booking request.',5],
    ['Esther Jepkoech','A clear and welcoming way to plan a flight.',5],['Collins Maina','The booking form was straightforward to use.',4],['Diana Atieno','Simple, clear and easy to navigate on my phone.',5]
  ].map((x,i)=>({id:Date.now()+100+i,name:x[0],note:x[1],rating:x[2],image:'',active:true,isDemo:false})),
  inquiries: []
};

function load(){
  if(!fs.existsSync(DB_FILE)) return structuredClone(defaultData);
  try { return JSON.parse(fs.readFileSync(DB_FILE,'utf8')); } catch { return structuredClone(defaultData); }
}
let data = load();
function save(){
  const tmp = `${DB_FILE}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(data,null,2));
  fs.renameSync(tmp, DB_FILE);
}
if(!fs.existsSync(DB_FILE)) save();

const sessions = new Map();
function newId(){ return crypto.randomBytes(12).toString('hex'); }
function escapeHtml(s=''){ return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function parseCookies(req){ return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),decodeURIComponent(v.slice(i+1))]})); }
function isAdmin(req){ const sid=parseCookies(req).ra_sid; return sid && sessions.get(sid); }
function send(res,status,body,type='text/html; charset=utf-8',headers={}){ res.writeHead(status,{'Content-Type':type,...headers});res.end(body); }
function redirect(res,to){send(res,302,'',undefined,{Location:to});}
async function body(req,limit=28*1024*1024){ return await new Promise((resolve,reject)=>{let chunks=[],size=0;req.on('data',c=>{size+=c.length;if(size>limit){reject(new Error('Payload too large'));req.destroy();return}chunks.push(c)});req.on('end',()=>{const raw=Buffer.concat(chunks).toString();try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)}); }
function staticFile(res,pathname){
  let file=path.join(PUBLIC_DIR,pathname.replace(/^\//,'')); if(pathname==='/') return false;
  if(file.includes('..')) return true;
  if(!fs.existsSync(file)||fs.statSync(file).isDirectory()) return false;
  const ext=path.extname(file).toLowerCase(); const types={'.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
  send(res,200,fs.readFileSync(file),types[ext]||'application/octet-stream'); return true;
}
function media(src,alt=''){ return src ? `<img class="contain" src="${escapeHtml(src)}" alt="${escapeHtml(alt)}">` : `<div class="media-placeholder">✈</div>`; }
function whatsappIcon(){ return `<svg class="wa-icon" viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M19.11 17.02c-.27-.14-1.59-.79-1.84-.88-.25-.09-.43-.14-.61.14-.18.27-.7.88-.86 1.06-.16.18-.32.2-.59.07-.27-.14-1.15-.43-2.18-1.38-.81-.72-1.36-1.61-1.52-1.88-.16-.27-.02-.42.12-.55.12-.12.27-.32.41-.48.14-.16.18-.27.27-.45.09-.18.05-.34-.02-.48-.07-.14-.61-1.47-.84-2.02-.22-.53-.45-.46-.61-.46h-.52c-.18 0-.48.07-.73.34-.25.27-.95.93-.95 2.27s.98 2.63 1.11 2.81c.14.18 1.93 2.95 4.68 4.13.65.28 1.16.45 1.56.57.66.21 1.26.18 1.73.11.53-.08 1.59-.65 1.81-1.27.23-.63.23-1.16.16-1.27-.06-.11-.25-.18-.52-.32z"/><path fill="currentColor" d="M16.02 3.05a12.95 12.95 0 0 0-11.1 19.63L3.2 28.5l5.94-1.69a12.97 12.97 0 1 0 6.88-23.76zm0 23.63c-2.06 0-4.08-.55-5.85-1.59l-.42-.25-3.53 1.01 1-3.44-.27-.44a10.69 10.69 0 1 1 9.07 4.71z"/></svg>`; }

function layout(title,content,admin=false){ const s=data.settings; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title>${s.favicon?`<link rel="icon" href="${escapeHtml(s.favicon)}">`:''}<link rel="stylesheet" href="/css/${admin?'admin':'site'}.css"></head><body>${admin?adminNav():publicNav()}${admin?'':'<div class="page-ambient" aria-hidden="true"></div>'}${content}${admin?'':'<script src="/js/site.js"></script>'}</body></html>`; }
function publicNav(){const s=data.settings;return `<header class="site-header"><div class="container nav-wrap"><a class="brand" href="/">${s.logo?`<img class="brand-logo contain" src="${escapeHtml(s.logo)}" alt="RENEGADE AIR logo">`:`<span class="brand-mark">✈</span>`}<span><strong>${escapeHtml(s.companyName)}</strong><small>AIR</small></span></a><button class="menu-btn" data-menu>☰</button><nav class="main-nav" data-nav><a href="#destinations">Destinations</a>${s.showGallery?'<a href="#gallery">Gallery</a>':''}<a href="#booking">Book</a>${s.showReviews?'<a href="#reviews">Reviews</a>':''}<a href="#contact">Contact</a></nav></div></header>`;}
function adminNav(){return `<header class="admin-header"><div class="container admin-nav"><a class="admin-brand" href="/admin">RENEGADE AIR <span>ADMIN</span></a><nav><a href="/admin">Dashboard</a><a href="/admin/settings">Settings</a><a href="/admin/destinations">Destinations</a><a href="/admin/gallery">Gallery</a><a href="/admin/fleet">Fleet</a><a href="/admin/reviews">Reviews</a><a href="/admin/inquiries">Inquiries</a></nav><form method="post" action="/admin/logout"><button>Logout</button></form></div></header>`;}
function home(){const s=data.settings;const dest=data.destinations.filter(x=>x.active).sort((a,b)=>a.sort-b.sort);const reviews=data.reviews.filter(x=>x.active).slice(-15).reverse();const gallery=data.gallery.filter(x=>x.active).slice(-50).reverse();const highlights=gallery.slice(0,4);const fleet=data.fleet.filter(x=>x.active).slice(-6).reverse();return layout(`${s.companyName} — ${s.tagline}`,`
<section class="hero"><div class="hero-media">${s.heroImage?`<img class="hero-image contain" src="${escapeHtml(s.heroImage)}" alt="RENEGADE AIR hero photograph">`:`<div class="hero-placeholder"><div class="plane-orbit">✈</div><p>Hero photograph will appear here after the admin uploads it.</p></div>`}</div><div class="container hero-content"><div class="hero-copy"><span class="eyebrow">✈ ${escapeHtml(s.companyName)}</span><h1>${escapeHtml(s.heroTitle)}</h1><p>${escapeHtml(s.heroText)}</p><div class="hero-actions"><a class="btn btn-primary" href="#booking">Book a Flight</a><a class="btn wa-button" href="https://wa.me/${escapeHtml(s.whatsapp)}" target="_blank" rel="noopener">${whatsappIcon()} <span>WhatsApp ${escapeHtml(s.phone)}</span></a></div></div></div></section>
<section class="section section-overlap"><div class="container stats-strip"><div><span class="stat-value">${escapeHtml(s.reviewCount)}+</span><span class="stat-label">Reviews</span></div><div><span class="stat-value">${dest.length}</span><span class="stat-label">Destinations</span></div><div><span class="stat-value">KSh</span><span class="stat-label">Fare display</span></div></div></section>
<section class="section destinations-section" id="destinations"><div class="container"><div class="section-head"><div><span class="eyebrow">DESTINATIONS</span><h2>Choose where you want to fly</h2></div><p>Explore the destinations currently listed by Renegade Air.</p></div><div class="destination-list">${dest.map(d=>`<a class="destination-row" href="#booking" data-destination="${escapeHtml(d.name)}"><span class="destination-name">${escapeHtml(d.name)}</span><span class="destination-fare">From KSh ${Number(d.fare).toLocaleString()}</span><span class="destination-arrow">→</span></a>`).join('')}</div></div></section>
${s.showGallery&&highlights.length?`<section class="section highlights-section"><div class="container"><div class="section-head highlights-head"><div><span class="eyebrow">TRAVEL HIGHLIGHTS</span><h2>Moments worth the journey</h2></div><div class="highlights-head-copy"><p>Explore four featured moments from the Renegade Air gallery, with a closer look at the experiences and places captured along the way.</p>${gallery.length>4?'<a class="text-link light-link" href="#gallery">View full gallery <span aria-hidden="true">↗</span></a>':''}</div></div><div class="highlights-grid">${highlights.map((g,i)=>`<article class="highlight-card ${i===0?'highlight-featured':''}"><div class="highlight-photo">${media(g.image,g.title)}<span class="highlight-badge">0${i+1}</span></div><div class="highlight-content"><span class="highlight-kicker">FEATURED MOMENT</span><h3>${escapeHtml(g.title)}</h3><p>${escapeHtml(g.description||'Discover more from the Renegade Air journey.')}</p></div></article>`).join('')}</div></div></section>`:''}
<section class="section tinted" id="booking"><div class="container booking-layout"><div><span class="eyebrow">BOOKING REQUEST</span><h2>Start your journey</h2><p>Send a request and the Renegade Air team can follow up with you. This is an inquiry form, not an automatic ticket purchase.</p><div class="contact-callout"><strong>${escapeHtml(s.phone)}</strong><span>Call or WhatsApp</span></div></div><form class="form-card" data-booking><div class="form-grid two"><label>Full name<input name="name" required></label><label>Phone<input name="phone" required></label></div><div class="form-grid two"><label>Email<input type="email" name="email"></label><label>From<input name="origin" placeholder="Your departure point"></label></div><div class="form-grid two"><label>Destination<select name="destination" required><option value="">Select destination</option>${dest.map(d=>`<option>${escapeHtml(d.name)}</option>`).join('')}</select></label><label>Travel date<input type="date" name="travel_date"></label></div><div class="form-grid two"><label>Passengers<input type="number" min="1" value="1" name="passengers"></label><label>Contact<input value="${escapeHtml(s.phone)}" readonly></label></div><label>Message<textarea name="message" rows="4" placeholder="Any extra details"></textarea></label><button class="btn btn-primary" type="submit">Send Booking Request</button><p class="fine-print" data-book-status>Your request will be visible to the website admin.</p></form></div></section>
${s.showGallery&&gallery.length?`<section class="section gallery-section" id="gallery"><div class="container"><div class="section-head"><div><span class="eyebrow">GALLERY</span><h2>More moments from Renegade Air</h2></div><p>Browse the full collection of images uploaded by the admin.</p></div><div class="gallery-grid">${gallery.map(g=>`<figure class="gallery-card">${media(g.image,g.title)}<figcaption><strong>${escapeHtml(g.title)}</strong><span>${escapeHtml(g.description||'')}</span></figcaption></figure>`).join('')}</div></div></section>`:''}
${s.showFleet&&fleet.length?`<section class="section tinted" id="fleet"><div class="container"><div class="section-head"><div><span class="eyebrow">FLEET</span><h2>Aircraft showcase</h2></div></div><div class="card-grid fleet-grid">${fleet.map(f=>`<article class="fleet-card"><div class="media-box">${media(f.image,f.name)}</div><div class="card-body"><h3>${escapeHtml(f.name)}</h3><p>${escapeHtml(f.description||'')}</p></div></article>`).join('')}</div></div></section>`:''}
${s.showReviews?`<section class="section reviews-section" id="reviews"><div class="container"><div class="section-head"><div><span class="eyebrow">REVIEWS</span><h2>What travelers are saying</h2></div><div class="review-count"><strong>${escapeHtml(s.reviewCount)}</strong><span>reviews</span></div></div><div class="reviews-grid">${reviews.map(r=>`<article class="review-card"><div class="review-top"><div class="avatar">${r.image?media(r.image,r.name):'👤'}</div><div><strong>${escapeHtml(r.name)}</strong><div class="stars">${'★'.repeat(Math.min(5,Math.max(1,r.rating)))}</div></div></div><p>“${escapeHtml(r.note)}”</p></article>`).join('')}</div></div></section>`:''}
<section class="section about"><div class="container about-grid"><div><span class="eyebrow">ABOUT</span><h2>${escapeHtml(s.aboutTitle)}</h2></div><div><p>${escapeHtml(s.aboutText)}</p><a class="btn btn-outline" href="#contact">Contact Renegade Air</a></div></div></section>
<footer class="footer" id="contact"><div class="container footer-grid"><div><div class="footer-brand">${escapeHtml(s.companyName)}</div><p>${escapeHtml(s.slogan)}</p></div><div><h3>Contact</h3><p><strong>${escapeHtml(s.phone)}</strong></p><p>${escapeHtml(s.email||'Contact us by phone or WhatsApp.')}</p><p>${escapeHtml(s.address)}</p></div><div><h3>Quick actions</h3><a class="text-link" href="tel:${escapeHtml(s.phone.replace(/\s+/g,''))}">Call ${escapeHtml(s.phone)}</a><a class="text-link" href="https://wa.me/${escapeHtml(s.whatsapp)}" target="_blank" rel="noopener">WhatsApp</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} ${escapeHtml(s.companyName)}</span><a href="/admin/login">Admin</a></div></footer><a class="whatsapp-float" href="https://wa.me/${escapeHtml(s.whatsapp)}" target="_blank" rel="noopener" aria-label="Chat with ${escapeHtml(s.companyName)} on WhatsApp">${whatsappIcon()}<span>Chat on WhatsApp</span></a>`);}

function adminPage(title,content){return layout(`${title} — RENEGADE AIR`,content,true);}
function formPage(kind){
  const defs={settings:'Website settings',destinations:'Destinations & fares',gallery:'Gallery',fleet:'Fleet',reviews:'Reviews'};return adminPage(defs[kind],`
  <main class="admin-main"><div class="container"><div class="page-head"><div><span class="eyebrow">ADMIN</span><h1>${defs[kind]}</h1></div></div>${kind==='settings'?settingsForm():''}${kind==='destinations'?destinationPage():''}${kind==='gallery'?galleryPage():''}${kind==='fleet'?fleetPage():''}${kind==='reviews'?reviewsPage():''}</div></main>`);
}
function settingsForm(){const s=data.settings;return `<form class="panel form" id="settings-form"><div class="form-section"><h2>Brand & contact</h2><div class="grid two"><label>Company name<input name="companyName" value="${escapeHtml(s.companyName)}"></label><label>Tagline<input name="tagline" value="${escapeHtml(s.tagline)}"></label><label>Phone<input name="phone" value="${escapeHtml(s.phone)}"></label><label>WhatsApp number<input name="whatsapp" value="${escapeHtml(s.whatsapp)}"></label><label>Email<input name="email" value="${escapeHtml(s.email)}"></label><label>Address<input name="address" value="${escapeHtml(s.address)}"></label></div></div><div class="form-section"><h2>Home content</h2><div class="grid"><label>Hero title<input name="heroTitle" value="${escapeHtml(s.heroTitle)}"></label><label>Hero text<textarea name="heroText">${escapeHtml(s.heroText)}</textarea></label><label>About title<input name="aboutTitle" value="${escapeHtml(s.aboutTitle)}"></label><label>About text<textarea name="aboutText">${escapeHtml(s.aboutText)}</textarea></label></div></div><div class="form-section"><h2>Review display</h2><div class="grid two"><label>Displayed review count<input name="reviewCount" value="${escapeHtml(s.reviewCount)}"></label><div class="notice">This number appears in the public reviews area and can be changed from here.</div></div></div><div class="form-section"><h2>Optional sections</h2><div class="grid two">${[['showFleet','Show fleet',s.showFleet],['showGallery','Show gallery',s.showGallery],['showReviews','Show reviews',s.showReviews]].map(x=>`<label>${x[1]}<select name="${x[0]}"><option value="1" ${x[2]?'selected':''}>Yes</option><option value="0" ${!x[2]?'selected':''}>No</option></select></label>`).join('')}</div></div><div class="form-section"><h2>Images</h2><div class="grid two">${fileField('logo','Logo',s.logo)}${fileField('heroImage','Hero photograph',s.heroImage)}${fileField('favicon','Favicon',s.favicon)}</div></div><button class="btn primary">Save settings</button><span class="save-status" id="save-status"></span></form>${adminClientScript()}`;}
function fileField(name,label,current){return `<label>${label}<input type="file" accept="image/*" data-file="${name}">${current?`<img class="thumb contain" src="${escapeHtml(current)}" alt="${escapeHtml(label)}">`:''}</label>`;}
function destinationPage(){return `<form class="panel form" data-entity="destination"><h2>Add destination</h2><div class="grid two"><label>Name<input name="name" required></label><label>Fare (KSh)<input type="number" min="0" name="fare" required></label></div><button class="btn primary">Add destination</button></form><div class="item-grid">${data.destinations.map(d=>`<form class="panel form" data-entity="destination" data-id="${d.id}"><div class="item-head"><h2>${escapeHtml(d.name)}</h2><span class="badge">${d.active?'Active':'Hidden'}</span></div><div class="grid two"><label>Name<input name="name" value="${escapeHtml(d.name)}"></label><label>Fare<input type="number" name="fare" value="${d.fare}"></label></div><label>Visibility<select name="active"><option value="1" ${d.active?'selected':''}>Active</option><option value="0" ${!d.active?'selected':''}>Hidden</option></select></label><div class="row-actions"><button class="btn primary">Save</button><button type="button" class="danger" data-delete="destination" data-id="${d.id}">Delete</button></div></form>`).join('')}</div>${entityScript()}`;}
function galleryPage(){return `<form class="panel form" data-entity="gallery"><h2>Add gallery image</h2><div class="grid two"><label>Title<input name="title" required></label><label>Category<input name="category" value="General"></label><label>Description<textarea name="description"></textarea></label><label>Image<input type="file" accept="image/*" data-file="image" required></label></div><button class="btn primary">Add image</button></form><div class="item-grid">${data.gallery.map(g=>`<form class="panel form" data-entity="gallery" data-id="${g.id}"><div class="item-head"><h2>${escapeHtml(g.title)}</h2></div><div class="grid two"><label>Title<input name="title" value="${escapeHtml(g.title)}"></label><label>Category<input name="category" value="${escapeHtml(g.category)}"></label><label>Description<textarea name="description">${escapeHtml(g.description||'')}</textarea></label><label>Replace image<input type="file" accept="image/*" data-file="image"><img class="thumb contain" src="${escapeHtml(g.image)}" alt="${escapeHtml(g.title)}"></label></div><label>Visibility<select name="active"><option value="1" ${g.active?'selected':''}>Visible</option><option value="0" ${!g.active?'selected':''}>Hidden</option></select></label><button class="btn primary">Save</button><button type="button" class="danger" data-delete="gallery" data-id="${g.id}">Delete</button></form>`).join('')}</div>${entityScript()}`;}
function fleetPage(){return `<form class="panel form" data-entity="fleet"><h2>Add aircraft entry</h2><div class="grid two"><label>Name/model<input name="name" required></label><label>Description<textarea name="description"></textarea></label><label>Image<input type="file" accept="image/*" data-file="image"></label></div><button class="btn primary">Add fleet item</button></form><div class="item-grid">${data.fleet.map(f=>`<form class="panel form" data-entity="fleet" data-id="${f.id}"><div class="item-head"><h2>${escapeHtml(f.name)}</h2></div><div class="grid two"><label>Name/model<input name="name" value="${escapeHtml(f.name)}"></label><label>Description<textarea name="description">${escapeHtml(f.description||'')}</textarea></label><label>Replace image<input type="file" accept="image/*" data-file="image">${f.image?`<img class="thumb contain" src="${escapeHtml(f.image)}" alt="${escapeHtml(f.name)}">`:''}</label></div><label>Visibility<select name="active"><option value="1" ${f.active?'selected':''}>Visible</option><option value="0" ${!f.active?'selected':''}>Hidden</option></select></label><button class="btn primary">Save</button><button type="button" class="danger" data-delete="fleet" data-id="${f.id}">Delete</button></form>`).join('')}</div>${entityScript()}`;}
function reviewsPage(){return `<div class="notice">Homepage shows up to 15 active reviews. The displayed review count is managed from Website Settings.</div><form class="panel form" data-entity="review"><h2>Add review</h2><div class="grid two"><label>Name<input name="name" required></label><label>Rating<select name="rating">${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label><label>Short note<textarea name="note" required></textarea></label><label>Photo<input type="file" accept="image/*" data-file="image"></label></div><button class="btn primary">Add review</button></form><div class="item-grid">${data.reviews.map(r=>`<form class="panel form" data-entity="review" data-id="${r.id}"><div class="item-head"><h2>${escapeHtml(r.name)}</h2></div><div class="grid two"><label>Name<input name="name" value="${escapeHtml(r.name)}"></label><label>Rating<select name="rating">${[5,4,3,2,1].map(n=>`<option value="${n}" ${r.rating===n?'selected':''}>${n}</option>`).join('')}</select></label><label>Short note<textarea name="note">${escapeHtml(r.note)}</textarea></label><label>Replace photo<input type="file" accept="image/*" data-file="image">${r.image?`<img class="thumb contain" src="${escapeHtml(r.image)}" alt="${escapeHtml(r.name)}">`:''}</label></div><label>Visibility<select name="active"><option value="1" ${r.active?'selected':''}>Visible</option><option value="0" ${!r.active?'selected':''}>Hidden</option></select></label><button class="btn primary">Save</button><button type="button" class="danger" data-delete="review" data-id="${r.id}">Delete</button></form>`).join('')}</div>${entityScript()}`;}
function adminClientScript(){return `<script>(function(){const f=document.getElementById('settings-form');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const out={};f.querySelectorAll('input[name],textarea[name],select[name]').forEach(x=>out[x.name]=x.type==='select-one'&&['0','1'].includes(x.value)?x.value:x.value);for(const i of f.querySelectorAll('[data-file]')){if(i.files[0])out[i.dataset.file]=await toData(i.files[0])}const r=await fetch('/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(out)});document.getElementById('save-status').textContent=r.ok?' Saved.':' Save failed.';});function toData(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)})}})()</script>`;}
function entityScript(){return `<script>(function(){document.querySelectorAll('[data-entity]').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();try{const out={};f.querySelectorAll('input[name],textarea[name],select[name]').forEach(x=>out[x.name]=x.value);for(const i of f.querySelectorAll('[data-file]')){if(i.files&&i.files[0])out[i.dataset.file]=await toData(i.files[0])}const type=f.dataset.entity; if(type==='gallery'){if(!String(out.title||'').trim()){alert('Please enter a title.');return}if(!out.image){alert('Please choose an image.');return}} if(type==='destination'&&!String(out.name||'').trim()){alert('Please enter a destination name.');return} if(type==='fleet'&&!String(out.name||'').trim()){alert('Please enter the aircraft name/model.');return} if(type==='review'&&(!String(out.name||'').trim()||!String(out.note||'').trim())){alert('Please enter the customer name and review note.');return}const id=f.dataset.id||'';const r=await fetch('/admin/entity/'+type+(id?'/'+id:''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(out)});const text=await r.text();if(r.ok)location.reload();else alert(text||'Unable to save.')}catch(err){alert(err.message||'Unable to save.')}}));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Delete this item?'))return;const r=await fetch('/admin/entity/'+b.dataset.delete+'/'+b.dataset.id,{method:'DELETE'});if(r.ok)location.reload() }));function toData(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=()=>rej(new Error('The selected image could not be read.'));fr.readAsDataURL(file)})}})()</script>`;}
function dashboard(){const s=data.settings;const stats=[data.destinations.length,data.gallery.length,data.fleet.length,data.reviews.length,data.inquiries.filter(x=>x.status==='New').length];return adminPage('Dashboard',`<main class="admin-main"><div class="container"><div class="page-head"><div><span class="eyebrow">ADMIN</span><h1>Dashboard</h1></div><a class="btn primary" href="/">View website</a></div><div class="stat-grid"><div><strong>${stats[0]}</strong><span>Destinations</span></div><div><strong>${stats[1]}</strong><span>Gallery items</span></div><div><strong>${stats[2]}</strong><span>Fleet items</span></div><div><strong>${stats[3]}</strong><span>Reviews</span></div><div><strong>${stats[4]}</strong><span>New inquiries</span></div></div><section class="panel"><div class="panel-head"><h2>Recent inquiries</h2><a class="text-link" href="/admin/inquiries">Open all</a></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Journey</th><th>Date</th><th>Status</th></tr></thead><tbody>${data.inquiries.slice(-8).reverse().map(i=>`<tr><td>${escapeHtml(i.name)}</td><td>${escapeHtml(i.origin||'—')} → ${escapeHtml(i.destination)}</td><td>${escapeHtml(i.travel_date||'—')}</td><td><span class="badge">${escapeHtml(i.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No inquiries yet.</td></tr>'}</tbody></table></div></section></div></main>`);}
function inquiryPage(){return adminPage('Inquiries',`<main class="admin-main"><div class="container"><div class="page-head"><div><span class="eyebrow">ADMIN</span><h1>Booking inquiries</h1></div></div><div class="panel table-wrap"><table><thead><tr><th>Customer</th><th>Journey</th><th>Travel date</th><th>Passengers</th><th>Contact</th><th>Status</th></tr></thead><tbody>${data.inquiries.slice().reverse().map(i=>`<tr><td><strong>${escapeHtml(i.name)}</strong><br><span class="muted">${escapeHtml(i.message||'')}</span></td><td>${escapeHtml(i.origin||'—')} → ${escapeHtml(i.destination)}</td><td>${escapeHtml(i.travel_date||'—')}</td><td>${i.passengers}</td><td>${escapeHtml(i.phone)}<br>${escapeHtml(i.email||'')}</td><td><select data-inquiry="${i.id}">${['New','Contacted','Confirmed','Completed','Cancelled'].map(st=>`<option ${i.status===st?'selected':''}>${st}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="6">No inquiries yet.</td></tr>'}</tbody></table></div></div></main><script>document.querySelectorAll('[data-inquiry]').forEach(s=>s.addEventListener('change',async()=>{await fetch('/admin/inquiries/'+s.dataset.inquiry,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})});location.reload()}))</script>`);}
function loginPage(error=''){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login — RENEGADE AIR</title><link rel="stylesheet" href="/css/site.css"><style>body{background:#f4f7fb;min-height:100vh;display:grid;place-items:center}.auth{width:min(420px,calc(100% - 24px));background:#fff;border:1px solid #dfe5ee;border-radius:20px;padding:24px;box-shadow:0 18px 50px rgba(6,22,46,.1)}.auth h1{margin:0 0 8px}.auth form{display:grid;gap:12px}.auth .btn{background:#0a1830;color:#fff;width:100%}.error{color:#9c1c1c}</style></head><body><div class="auth"><span class="eyebrow">RENEGADE AIR</span><h1>Admin login</h1><p>Manage the public website content.</p>${error?`<p class="error">${escapeHtml(error)}</p>`:''}<form method="post" action="/admin/login"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button class="btn" type="submit">Sign in</button></form></div></body></html>`;}
function decodeUpload(v){ if(!v)return ''; const m=String(v).match(/^data:(image\/(?:jpeg|png|webp|gif|svg\+xml));base64,(.+)$/s); if(!m) throw new Error('Only JPEG, PNG, WebP, GIF, or SVG images are allowed.'); const buf=Buffer.from(m[2],'base64'); if(buf.length>8*1024*1024) throw new Error('Image must be 8MB or smaller.'); const ext={jpeg:'jpg','png':'png','webp':'webp','gif':'gif','svg+xml':'svg'}[m[1].split('/')[1]];const file=`${Date.now()}-${crypto.randomBytes(4).toString('hex')}.${ext}`;fs.writeFileSync(path.join(UPLOAD_DIR,file),buf);return `/uploads/${file}`;}
function removeFile(ref){if(!ref||!ref.startsWith('/uploads/'))return;try{fs.unlinkSync(path.join(UPLOAD_DIR,path.basename(ref)))}catch{}}
function mergeUpload(obj,key,old=''){if(!obj[key])return old;const next=decodeUpload(obj[key]);removeFile(old);return next;}

const server=http.createServer(async(req,res)=>{
  try{
    const p=url.parse(req.url,true).pathname;
    if(req.method==='GET' && p.startsWith('/uploads/')){const fp=path.join(UPLOAD_DIR,path.basename(p));if(fs.existsSync(fp)){const ext=path.extname(fp).toLowerCase();const types={'.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif','.svg':'image/svg+xml'};return send(res,200,fs.readFileSync(fp),types[ext]||'application/octet-stream')}return send(res,404,'Not found')}
    if(req.method==='GET' && staticFile(res,p)) return;
    if(req.method==='GET' && p==='/health') return send(res,200,JSON.stringify({ok:true,service:'renegade-air'}),'application/json');
    if(req.method==='GET' && p==='/') return send(res,200,home());
    if(req.method==='POST' && p==='/booking'){const b=await body(req,2*1024*1024);if(!b.name||!b.phone||!b.destination)return send(res,400,'Name, phone and destination are required.','text/plain');data.inquiries.push({id:Date.now(),name:String(b.name).trim(),phone:String(b.phone).trim(),email:String(b.email||'').trim(),origin:String(b.origin||'').trim(),destination:String(b.destination).trim(),travel_date:String(b.travel_date||'').trim(),passengers:Math.max(1,parseInt(b.passengers,10)||1),message:String(b.message||'').trim(),status:'New',createdAt:new Date().toISOString()});save();return send(res,200,JSON.stringify({ok:true}),'application/json');}
    if(req.method==='GET' && p==='/admin/login') return send(res,200,loginPage());
    if(req.method==='POST' && p==='/admin/login'){const raw=await new Promise((resolve,reject)=>{let c='';req.on('data',x=>c+=x);req.on('end',()=>resolve(new URLSearchParams(c)))});if(raw.get('email')===ADMIN_EMAIL&&raw.get('password')===ADMIN_PASSWORD){const sid=newId();sessions.set(sid,{email:ADMIN_EMAIL,createdAt:Date.now()});return send(res,302,'','text/plain',{'Location':'/admin','Set-Cookie':`ra_sid=${encodeURIComponent(sid)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`});}return send(res,401,loginPage('Invalid email or password.'));}
    if(req.method==='POST' && p==='/admin/logout'){const sid=parseCookies(req).ra_sid;sessions.delete(sid);return redirect(res,'/admin/login');}
    if(p.startsWith('/admin')){if(!isAdmin(req)) return redirect(res,'/admin/login');
      if(req.method==='GET'&&p==='/admin')return send(res,200,dashboard());
      if(req.method==='GET'&&p==='/admin/settings')return send(res,200,formPage('settings'));
      if(req.method==='POST'&&p==='/admin/settings'){const b=await body(req);const s=data.settings;for(const k of ['companyName','tagline','phone','whatsapp','email','address','heroTitle','heroText','aboutTitle','aboutText','reviewCount'])if(b[k]!==undefined)s[k]=String(b[k]);for(const k of ['showFleet','showGallery','showReviews'])s[k]=b[k]==='1'||b[k]===true;s.logo=mergeUpload(b,'logo',s.logo);s.heroImage=mergeUpload(b,'heroImage',s.heroImage);s.favicon=mergeUpload(b,'favicon',s.favicon);s.reviewCountIsDemo=false;save();return send(res,200,JSON.stringify({ok:true}),'application/json');}
      if(req.method==='GET'&&p==='/admin/destinations')return send(res,200,formPage('destinations'));
      if(req.method==='GET'&&p==='/admin/gallery')return send(res,200,formPage('gallery'));
      if(req.method==='GET'&&p==='/admin/fleet')return send(res,200,formPage('fleet'));
      if(req.method==='GET'&&p==='/admin/reviews')return send(res,200,formPage('reviews'));
      if(req.method==='GET'&&p==='/admin/inquiries')return send(res,200,inquiryPage());
      const em=p.match(/^\/admin\/entity\/(destination|gallery|fleet|review)(?:\/(\d+))?$/);
      if(em&&req.method==='POST'){const b=await body(req);const type=em[1],id=em[2]?Number(em[2]):0;const collection={destination:'destinations',gallery:'gallery',fleet:'fleet',review:'reviews'}[type];if(!id){const item={id:Date.now()+Math.floor(Math.random()*1000),active:true};if(type==='destination'){item.name=String(b.name||'').trim();item.fare=Number(b.fare)||0;item.description=String(b.description||'').trim();item.image=decodeUpload(b.image||'');item.sort=data.destinations.length}else if(type==='gallery'){item.title=String(b.title||'').trim();item.category=String(b.category||'General').trim();item.description=String(b.description||'').trim();item.image=decodeUpload(b.image||'')}else if(type==='fleet'){item.name=String(b.name||'').trim();item.description=String(b.description||'').trim();item.image=decodeUpload(b.image||'')}else{item.name=String(b.name||'').trim();item.note=String(b.note||'').trim();item.rating=Math.min(5,Math.max(1,Number(b.rating)||5));item.image=decodeUpload(b.image||'');item.isDemo=false}if(!item.name && type!=='gallery')return send(res,400,'Required information is missing: name.','text/plain');if(type==='gallery'&&!item.title)return send(res,400,'Required information is missing: title.','text/plain');if(type==='gallery'&&!item.image)return send(res,400,'Required information is missing: image.','text/plain');data[collection].push(item);save();return send(res,200,JSON.stringify({ok:true}),'application/json');}
        const idx=data[collection].findIndex(x=>x.id===id);if(idx<0)return send(res,404,'Not found');const item=data[collection][idx];if(type==='destination'){item.name=String(b.name||item.name).trim();item.fare=Number(b.fare)||0;item.description=String(b.description||'').trim();item.active=b.active==='1';item.image=mergeUpload(b,'image',item.image)}else if(type==='gallery'){item.title=String(b.title||item.title).trim();item.category=String(b.category||'General').trim();item.description=String(b.description||'').trim();item.active=b.active==='1';item.image=mergeUpload(b,'image',item.image)}else if(type==='fleet'){item.name=String(b.name||item.name).trim();item.description=String(b.description||'').trim();item.active=b.active==='1';item.image=mergeUpload(b,'image',item.image)}else{item.name=String(b.name||item.name).trim();item.note=String(b.note||item.note).trim();item.rating=Math.min(5,Math.max(1,Number(b.rating)||5));item.active=b.active==='1';item.image=mergeUpload(b,'image',item.image);item.isDemo=false}save();return send(res,200,JSON.stringify({ok:true}),'application/json');}
      if(em&&req.method==='DELETE'){const collection={destination:'destinations',gallery:'gallery',fleet:'fleet',review:'reviews'}[em[1]],id=Number(em[2]);const idx=data[collection].findIndex(x=>x.id===id);if(idx<0)return send(res,404,'Not found');removeFile(data[collection][idx].image);data[collection].splice(idx,1);save();return send(res,200,JSON.stringify({ok:true}),'application/json');}
      const im=p.match(/^\/admin\/inquiries\/(\d+)$/);if(im&&req.method==='POST'){const b=await body(req);const item=data.inquiries.find(x=>x.id===Number(im[1]));if(!item)return send(res,404,'Not found');if(['New','Contacted','Confirmed','Completed','Cancelled'].includes(b.status))item.status=b.status;save();return send(res,200,JSON.stringify({ok:true}),'application/json');}
    }
    return send(res,404,'Page not found','text/plain');
  }catch(err){console.error(err);return send(res,500,err.message||'Server error','text/plain');}
});

server.listen(PORT,'0.0.0.0',()=>console.log(`RENEGADE AIR running on http://localhost:${PORT}`));
